/**
 * @coderef-semantic: 1.0.0
 * @layer service
 * @capability legacy-write-guard
 * @exports LegacyWriteOptions, isPipelineOwnedCoderefDir, assertLegacyWriteAllowed
 * @used_by src/fileGeneration/saveIndex.ts, src/fileGeneration/generateContext.ts, src/fileGeneration/buildDependencyGraph.ts, src/fileGeneration/detectPatterns.ts, src/fileGeneration/analyzeCoverage.ts, src/fileGeneration/validateReferences.ts, src/fileGeneration/detectDrift.ts, src/fileGeneration/generateDiagrams.ts
 */

/**
 * Legacy write guard — WO-UNIFIED-PIPELINE-LEGACY-SURFACE-BOUNDARY-001 P2-T1.
 *
 * PipelineOrchestrator generators are the only production writers of canonical
 * .coderef artifact paths. The retained legacy fileGeneration writers remain
 * available for standalone/unpopulated directories (semver compatibility), but
 * they MUST NOT silently replace a pipeline-generated artifact with an
 * incompatible schema under the same filename.
 *
 * Ownership marker: `.coderef/manifest.json` is written exclusively by the
 * pipeline GraphGenerator on every populate. Its presence marks the .coderef
 * dir as pipeline-owned, and every guarded legacy writer refuses to write
 * there unless the caller passes `{ force: true }`.
 */

import * as fs from 'fs';
import * as path from 'path';

export interface LegacyWriteOptions {
  /** Override the pipeline-owned guard and write anyway. */
  force?: boolean;
}

/** True when `.coderef/manifest.json` exists — i.e. populate owns this dir. */
export function isPipelineOwnedCoderefDir(projectPath: string): boolean {
  return fs.existsSync(path.join(projectPath, '.coderef', 'manifest.json'));
}

/**
 * Throw when a legacy writer targets a pipeline-owned .coderef dir without
 * an explicit force override.
 */
export function assertLegacyWriteAllowed(
  projectPath: string,
  artifact: string,
  options?: LegacyWriteOptions,
): void {
  if (options?.force) return;
  if (isPipelineOwnedCoderefDir(projectPath)) {
    throw new Error(
      `Refusing to write ${artifact}: this .coderef directory is pipeline-owned ` +
        `(canonical artifacts generated by populate-coderef are present). ` +
        `Re-run \`populate-coderef ${projectPath}\` to regenerate canonical artifacts, ` +
        `or pass { force: true } to overwrite deliberately.`,
    );
  }
}
