/**
 * @coderef-semantic: 1.0.0
 * @layer test_support
 * @capability api-surface-projection-and-mcp-tests
 */

/**
 * WO-API-SURFACE-MAPPING-RECONNECT-AND-GRAPH-ELEVATION-001 Phase 3.
 *
 * Two things are under test here, and the second is the workorder's headline
 * payoff:
 *
 *   1. The `api` block of the map projection, including its presence rule —
 *      absent means the API surface is UNKNOWN, never that it is empty.
 *   2. AMENDMENT 3 — that the EXISTING graph MCP tools cross the network
 *      boundary, not just the new one. P2 taught src/query to traverse the
 *      endpoint edges, but nothing asserted it at the surface agents actually
 *      consume. A library test passing while the MCP surface returns nothing
 *      would leave the feature shipped and unusable.
 *
 * HERMETIC: a synthetic fixture repo in tmp, matching the mcp-map-parity
 * precedent. The live .coderef/ is regenerated by other suites mid-run, which
 * makes assertions against it racy.
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { buildToolHandlers } from '../../src/cli/coderef-mcp-server.js';
import { projectMapData } from '../../src/map/project-map-data.js';
import { computeApiSurface } from '../../src/map/api-surface.js';
// ONE fixture definition, shared with the asset suites that render this block
// (WO-WIRE-THE-MAPDATA-API-BLOCK-INTO-THE-MAP-001 P1-T2 / ADJ-01). It lived
// here first; it moved so the viewer and dashboard tests assert against the
// same repo these projection tests do, rather than a second copy that can drift.
import {
  CLIENT,
  HANDLER,
  ORPHAN_HANDLER,
  EP_USERS,
  EP_ORPHAN,
  graphFixture,
  writeFixtureRepo,
  apiSurfaceFixture,
} from '../fixtures/api-surface-repo/index.js';

// Referenced by the AMENDMENT 3 blocks below; re-exported names keep those
// assertions reading exactly as they did before the extraction.
void ORPHAN_HANDLER;

let repo: string;
let repoNoRoutes: string;

beforeAll(() => {
  repo = fs.mkdtempSync(path.join(os.tmpdir(), 'coderef-api-surface-'));
  repoNoRoutes = fs.mkdtempSync(path.join(os.tmpdir(), 'coderef-api-nodata-'));
  writeFixtureRepo(repo, true);
  writeFixtureRepo(repoNoRoutes, false);
});

afterAll(() => {
  for (const dir of [repo, repoNoRoutes]) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

describe('api-surface projection', () => {
  it('folds endpoints, handlers, callers and network edges', () => {
    const data = projectMapData(repo);
    expect(data.meta.schemaVersion).toBe('1.7.0');
    const api = data.api!;
    expect(api.summary.endpointCount).toBe(2);
    expect(api.summary.resolvedCallCount).toBe(1);
    expect(api.summary.unmatchedCallCount).toBe(2);

    const users = api.endpoints.find(e => e.id === EP_USERS)!;
    expect(users.handlers).toEqual(['server/users.ts']);
    expect(users.callers).toEqual(['src/client.ts']);
    expect(users.orphaned).toBe(false);
  });

  it('marks an endpoint with no resolved caller as orphaned', () => {
    const api = projectMapData(repo).api!;
    const orphan = api.endpoints.find(e => e.id === EP_ORPHAN)!;
    expect(orphan.orphaned).toBe(true);
    expect(orphan.callers).toEqual([]);
    expect(api.summary.orphanedCount).toBe(1);
  });

  it('records network edges SEPARATELY from module edges', () => {
    // An import and an HTTP request are different kinds of coupling; collapsing
    // them would hide a process boundary from every file-graph consumer.
    const data = projectMapData(repo);
    expect(data.api!.networkEdges).toEqual([
      { source: 'src/client.ts', target: 'server/users.ts', endpoints: [EP_USERS] },
    ]);
    expect(data.edges.some(e => e.kinds.calls_endpoint || e.kinds.serves_endpoint)).toBe(false);
  });

  it('records every unmatched call with the reason it did not bind', () => {
    const api = projectMapData(repo).api!;
    expect(api.summary.byReason).toEqual({
      endpoint_not_in_project: 1,
      absolute_url_external_origin: 1,
    });
    const ghost = api.unmatchedCalls.find(c => c.path === '/api/ghost')!;
    expect(ghost.status).toBe('unresolved');
    expect(ghost.line).toBe(20);
    expect(ghost.rawPath).toBe('/api/ghost');
    const vendor = api.unmatchedCalls.find(c => c.path === '/v1/models')!;
    expect(vendor.status).toBe('external');
  });

  it('ABSENT block when routes.json was never produced — no-data, not zero', () => {
    const data = projectMapData(repoNoRoutes);
    expect(data.api).toBeUndefined();
    expect(data.meta.warnings.some(w => w.includes('api block omitted'))).toBe(true);
    expect(data.meta.warnings.some(w => w.includes('UNKNOWN'))).toBe(true);
  });

  it('the shared apiSurfaceFixture() matches what the pipeline actually emits', () => {
    // The asset suites render apiSurfaceFixture() directly — they drive the
    // browser renderers, not the pipeline, so they never touch projectMapData.
    // That convenience copy is only trustworthy while it equals the real
    // projection. Without this assertion the fixture could drift and every
    // viewer/dashboard test would keep passing against a shape the pipeline no
    // longer produces (WO-WIRE-THE-MAPDATA-API-BLOCK-INTO-THE-MAP-001 P1-T2).
    expect(projectMapData(repo).api).toStrictEqual(apiSurfaceFixture());
  });

  it('is deterministic and declares truncation rather than implying completeness', () => {
    const graph = graphFixture();
    const first = computeApiSurface(graph.nodes, graph.edges, new Map());
    const second = computeApiSurface(graph.nodes, graph.edges, new Map());
    expect(first).toStrictEqual(second);

    const capped = computeApiSurface(graph.nodes, graph.edges, new Map(), { unmatchedCap: 1 });
    expect(capped.unmatchedCalls).toHaveLength(1);
    expect(capped.summary.unmatchedCallCount).toBe(2); // summary stays complete
    expect(capped.warnings.some(w => w.includes('truncated'))).toBe(true);
  });
});

describe('MCP api_surface tool', () => {
  it('returns the endpoint inventory with its caveat note', () => {
    const result: any = buildToolHandlers(repo).api_surface({});
    expect(result.no_data).toBeUndefined();
    expect(result.total).toBe(2);
    expect(result.summary.orphanedCount).toBe(1);
    expect(result.unmatched_calls).toHaveLength(2);
    expect(result.network_edges).toHaveLength(1);
    expect(result.note).toContain('NO RESOLVED CALLER WAS FOUND IN THIS REPO');
  });

  it('reports no_data — never zero — when route detection never ran', () => {
    const result: any = buildToolHandlers(repoNoRoutes).api_surface({});
    expect(result.no_data).toBe(true);
    expect(result.reason).toBe('routes_artifact_absent');
    expect(result.endpoints).toBeUndefined();
    expect(result.warning).toContain('UNKNOWN');
    expect(result.warning).toContain('NOT a report of zero endpoints');
  });

  it('filters by substring and by orphaned_only', () => {
    const handlers = buildToolHandlers(repo);
    expect((handlers.api_surface({ filter: 'reports' }) as any).total).toBe(1);
    expect((handlers.api_surface({ filter: 'USERS' }) as any).total).toBe(1);
    const orphans: any = handlers.api_surface({ orphaned_only: true });
    expect(orphans.endpoints.map((e: any) => e.id)).toEqual([EP_ORPHAN]);
  });

  it('paginates without letting a cap read as completeness', () => {
    const page: any = buildToolHandlers(repo).api_surface({ limit: 1 });
    expect(page.endpoints).toHaveLength(1);
    expect(page.total).toBe(2);
    expect(page.has_more).toBe(true);
  });

  it('honors the concise response format', () => {
    const result: any = buildToolHandlers(repo).api_surface({ response_format: 'concise' });
    expect(result.format).toBe('concise');
    expect(result.endpoints[0]).toHaveProperty('orphaned');
    expect(result.endpoints[0]).not.toHaveProperty('handlers.0');
  });
});

describe('AMENDMENT 3 — the EXISTING graph MCP tools cross the network boundary', () => {
  it('what_calls(endpoint) names the client file', () => {
    const result: any = buildToolHandlers(repo).what_calls({ element: EP_USERS });
    const ids = (result.callers ?? result.results ?? []).map((n: any) => n.id ?? n);
    expect(ids).toContain(CLIENT);
  });

  it('what_calls(handler file) names the endpoint it serves', () => {
    const result: any = buildToolHandlers(repo).what_calls({ element: HANDLER });
    const ids = (result.callers ?? result.results ?? []).map((n: any) => n.id ?? n);
    expect(ids).toContain(EP_USERS);
  });

  it('impact_of(handler file) reaches the CLIENT — blast radius crosses the boundary', () => {
    // This is REC-002's headline claim. Before P2 this returned only the modules
    // that IMPORT the handler; an HTTP caller was invisible.
    const result: any = buildToolHandlers(repo).impact_of({ element: HANDLER, max_depth: 5 });
    // The envelope reports affected FILES plus a sample of dependent nodes.
    expect(result.files.map((f: any) => f.file)).toContain('src/client.ts');
    const sampled = (result.sample_dependents ?? []).map((n: any) => n.id ?? n);
    expect(sampled).toContain(CLIENT);
    // The endpoint is the hop it travelled through, so it appears too.
    expect(sampled).toContain(EP_USERS);
    expect(result.transitive_dependents).toBeGreaterThanOrEqual(2);
  });

  it('path_between(client, handler) walks client -> endpoint -> handler', () => {
    const result: any = buildToolHandlers(repo).path_between({ source: CLIENT, target: HANDLER });
    const found = result.found ?? result.paths?.length > 0;
    expect(found).toBeTruthy();
    const hops = (result.path ?? result.paths?.[0]?.path ?? []).map((n: any) => n.id ?? n);
    expect(hops).toEqual([CLIENT, EP_USERS, HANDLER]);
  });

  it('an orphaned endpoint yields an EMPTY caller list, which is an answer', () => {
    // Empty here means "no resolved caller in this repo" — the tool answered.
    // It must not be confused with the no_data case above, where route detection
    // never ran at all.
    const result: any = buildToolHandlers(repo).what_calls({ element: EP_ORPHAN });
    const ids = (result.callers ?? result.results ?? []).map((n: any) => n.id ?? n);
    expect(ids).toEqual([]);
  });
});
