graph TD
  _Fn_demo_all_modules_ts_section_64["section"]
  _Fn_demo_all_modules_ts_success_70["success"]
  _Fn_demo_all_modules_ts_info_74["info"]
  _Fn_demo_all_modules_ts_main_78["main"]
  _I_examples_nextjs_api_route_ts_ApiResponse_27["ApiResponse"]
  _I_examples_nextjs_api_route_ts_ScanRequest_40["ScanRequest"]
  _I_examples_nextjs_api_route_ts_ScanResult_52["ScanResult"]
  _C_examples_nextjs_api_route_ts_POST_91["POST"]
  _I_examples_nextjs_api_route_ts_ValidationResult_182["ValidationResult"]
  _Fn_examples_nextjs_api_route_ts_validateScanRequest_191["validateScanRequest"]
  _Fn_examples_nextjs_api_route_ts_mapErrorToResponse_272["mapErrorToResponse"]
  _Fn_examples_nextjs_api_route_ts_calculateSummary_328["calculateSummary"]
  _C_examples_nextjs_api_route_ts_GET_372["GET"]
  _I_examples_plugins_example_detector_src_detectors_fastapi_ts_DetectionResult_12["DetectionResult"]
  _I_examples_plugins_example_detector_src_detectors_fastapi_ts_CodeDetector_24["CodeDetector"]
  _I_examples_plugins_example_detector_src_hooks_route_relationships_ts_CustomEdge_12["CustomEdge"]
  _I_examples_plugins_example_detector_src_hooks_route_relationships_ts_CodeElement_19["CodeElement"]
  _I_examples_plugins_example_detector_src_hooks_route_relationships_ts_GraphBuilderContext_29["GraphBuilderContext"]
  _I_examples_plugins_example_detector_src_hooks_route_relationships_ts_GraphHook_36["GraphHook"]
  _Fn_scripts_scan_cli_test_scan_cli_test_ts_createTestProject_27["createTestProject"]
  _I_src_adapter_graph_to_elements_ts_ConversionOptions_20["ConversionOptions"]
  _Fn_src_adapter_graph_to_elements_ts_convertGraphToElements_47["convertGraphToElements"]
  _Fn_src_adapter_graph_to_elements_ts_getConversionStats_141["getConversionStats"]
  _I_src_analyzer_analyzer_service_ts_AnalysisResult_33["AnalysisResult"]
  _Cl_src_analyzer_analyzer_service_ts_AnalyzerService_49["AnalyzerService"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_setElementMap_64["AnalyzerService.setElementMap"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_analyze_73["AnalyzerService.analyze"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_createAnalysisResult_112["AnalyzerService.createAnalysisResult"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_getCallers_141["AnalyzerService.getCallers"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_getCallees_151["AnalyzerService.getCallees"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_getDependents_161["AnalyzerService.getDependents"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_getDependencies_171["AnalyzerService.getDependencies"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_traverse_181["AnalyzerService.traverse"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_detectCircularDependencies_195["AnalyzerService.detectCircularDependencies"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_findShortestPath_205["AnalyzerService.findShortestPath"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_findAllPaths_215["AnalyzerService.findAllPaths"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_getGraph_229["AnalyzerService.getGraph"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_clearCache_236["AnalyzerService.clearCache"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_exportGraphAsJSON_245["AnalyzerService.exportGraphAsJSON"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_saveGraph_255["AnalyzerService.saveGraph"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_loadGraph_275["AnalyzerService.loadGraph"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_findFiles_312["AnalyzerService.findFiles"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_getGraphStatistics_339["AnalyzerService.getGraphStatistics"]
  _M_src_analyzer_analyzer_service_ts_AnalyzerService_findIsolatedNodes_346["AnalyzerService.findIsolatedNodes"]
  _I_src_analyzer_ast_element_scanner_ts_ASTScanResult_30["ASTScanResult"]
  _Cl_src_analyzer_ast_element_scanner_ts_ASTElementScanner_45["ASTElementScanner"]
  _M_src_analyzer_ast_element_scanner_ts_ASTElementScanner_scanFile_56["ASTElementScanner.scanFile"]
  _M_src_analyzer_ast_element_scanner_ts_ASTElementScanner_scanFiles_78["ASTElementScanner.scanFiles"]
  _M_src_analyzer_ast_element_scanner_ts_ASTElementScanner_parseElements_112["ASTElementScanner.parseElements"]
  _M_src_analyzer_ast_element_scanner_ts_ASTElementScanner_collectExportedNames_155["ASTElementScanner.collectExportedNames"]
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_demo_all_modules_ts --> 
  _File_examples_nextjs_api_route_ts --> 
  _File_examples_nextjs_api_route_ts --> 
  _File_examples_nextjs_api_route_ts --> 
  _File_examples_nextjs_api_route_ts --> 
  _File_examples_nextjs_api_route_ts --> 
  _File_examples_nextjs_api_route_ts --> 
  _File_examples_plugins_example_detector_src_index_ts --> 
  _File_examples_plugins_example_detector_src_index_ts --> 
  _File_scripts_scan_cli_test_scan_cli_test_ts --> 
  _File_scripts_scan_cli_test_scan_cli_test_ts --> 
  _File_scripts_scan_cli_test_scan_cli_test_ts --> 
  _File_scripts_scan_cli_test_scan_cli_test_ts --> 
  _File_scripts_scan_cli_test_scan_cli_test_ts --> 
  _File_scripts_scan_cli_test_scan_cli_test_ts --> 
  _File_scripts_scan_cli_test_scan_cli_test_ts --> 
  _File_scripts_scan_cli_test_scan_cli_test_ts --> 
  _File_scripts_scan_cli_test_scan_cli_test_ts --> 
  _File_scripts_scan_cli_test_scan_cli_test_ts --> 
  _File_scripts_scan_cli_test_scan_cli_test_ts --> 
  _File_src_adapter_graph_to_elements_ts --> 
  _File_src_adapter_graph_to_elements_ts --> 
  _File_src_adapter_graph_to_elements_ts --> 
  _File_src_analyzer_analyzer_service_ts --> 
  _File_src_analyzer_analyzer_service_ts --> 
  _File_src_analyzer_analyzer_service_ts --> 
  _File_src_analyzer_analyzer_service_ts --> 
  _File_src_analyzer_analyzer_service_ts --> 
  _File_src_analyzer_analyzer_service_ts --> 
  _File_src_analyzer_analyzer_service_ts --> 
  _File_src_analyzer_analyzer_service_ts --> 
  _File_src_analyzer_analyzer_service_ts --> 
  _File_src_analyzer_analyzer_service_ts --> 
  _File_src_analyzer_analyzer_service_ts --> 
  _File_src_analyzer_ast_element_scanner_ts --> 
  _File_src_analyzer_ast_element_scanner_ts --> 
  _File_src_analyzer_ast_element_scanner_ts --> 
  _File_src_analyzer_call_detector_ts --> 
  _File_src_analyzer_call_detector_ts --> 
  _File_src_analyzer_config_analyzer_ts --> 
  _File_src_analyzer_config_analyzer_ts --> 
  _File_src_analyzer_contract_detector_ts --> 
  _File_src_analyzer_contract_detector_ts --> 
  _File_src_analyzer_database_detector_ts --> 
  _File_src_analyzer_database_detector_ts --> 
  _File_src_analyzer_dependency_analyzer_ts --> 
  _File_src_analyzer_dependency_analyzer_ts --> 
  _File_src_analyzer_dependency_analyzer_ts --> 
  _File_src_analyzer_dependency_analyzer_ts --> 
  _File_src_analyzer_design_pattern_detector_ts --> 
  _File_src_analyzer_design_pattern_detector_ts --> 
  _File_src_analyzer_docs_analyzer_ts --> 
  _File_src_analyzer_docs_analyzer_ts --> 
  _File_src_analyzer_dynamic_import_detector_ts --> 
  _File_src_analyzer_dynamic_import_detector_ts --> 
  _File_src_analyzer_dynamic_import_detector_ts --> 
  _File_src_analyzer_entry_detector_ts --> 
  _File_src_analyzer_entry_detector_ts --> 
  _File_src_analyzer_frameworks_express_detector_ts --> 
  _File_src_analyzer_frameworks_express_detector_ts --> 
  _File_src_analyzer_frameworks_express_detector_ts --> 
  _File_src_analyzer_frameworks_fastapi_detector_ts --> 
  _File_src_analyzer_frameworks_fastapi_detector_ts --> 
  _File_src_analyzer_frameworks_fastapi_detector_ts --> 
  _File_src_analyzer_frameworks_flask_detector_ts --> 
  _File_src_analyzer_frameworks_flask_detector_ts --> 
  _File_src_analyzer_frameworks_flask_detector_ts --> 
  _File_src_analyzer_frameworks_nextjs_detector_ts --> 
  _File_src_analyzer_frameworks_nextjs_detector_ts --> 
  _File_src_analyzer_frameworks_nextjs_detector_ts --> 
  _File_src_analyzer_frameworks_nextjs_detector_ts --> 
  _File_src_analyzer_frameworks_nuxt_detector_ts --> 
  _File_src_analyzer_frameworks_nuxt_detector_ts --> 
  _File_src_analyzer_frameworks_nuxt_detector_ts --> 
  _File_src_analyzer_frameworks_remix_detector_ts --> 
  _File_src_analyzer_frameworks_remix_detector_ts --> 
  _File_src_analyzer_frameworks_remix_detector_ts --> 
  _File_src_analyzer_frameworks_sveltekit_detector_ts --> 
  _File_src_analyzer_frameworks_sveltekit_detector_ts --> 
  _File_src_analyzer_frameworks_sveltekit_detector_ts --> 
  _File_src_analyzer_frontend_call_parsers_test_ts --> 